package ddfaktury.entity;
// Generated 2011-12-20 15:10:35 by Hibernate Tools 3.2.1.GA

import ddfaktury.ui.Out;
import ddfaktury.ui.Error;
import ddfaktury.utils.HibernateUtil;
import java.util.List;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 * Sprzedawca generated by hbm2java
 */
public class Sprzedawca  implements java.io.Serializable {


     private Integer id;
     private String nazwa;
     private String miejscowosc;
     private String kod;
     private String adres;
     private String nip;
     private String bank;
     private String numerKonta;

    public Sprzedawca() {
        
    }

    public Sprzedawca(String nazwa, String miejscowosc, String kod, String adres, String nip, String bank, String numerKonta) {
       this.nazwa = nazwa;
       this.miejscowosc = miejscowosc;
       this.kod = kod;
       this.adres = adres;
       this.nip = nip;
       this.bank = bank;
       this.numerKonta = numerKonta;
    }

    public String getBank() {
        return bank;
    }

    public void setBank(String bank) {
        this.bank = bank;
    }

    public String getNumerKonta() {
        return numerKonta;
    }

    public void setNumerKonta(String numerKonta) {
        this.numerKonta = numerKonta;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public String getMiejscowosc() {
        return this.miejscowosc;
    }
    
    public void setMiejscowosc(String miejscowosc) {
        this.miejscowosc = miejscowosc;
    }
    public String getKod() {
        return this.kod;
    }
    
    public void setKod(String kod) {
        this.kod = kod;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public String getNip() {
        return this.nip;
    }
    
    public void setNip(String nip) {
        this.nip = nip;
    }

    public static Sprzedawca get(){
                SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
                Session session = sessionFactory.getCurrentSession();
                session.beginTransaction();
                List<Sprzedawca> result = session.createQuery("from Sprzedawca").list();
                session.getTransaction().commit();
        return result.get(0);
    }

    public static void add(String nazwa, String miejscowosc, String kod, String adres, String nip, String bank, String numerKonta) {
        Session sessionadd = HibernateUtil.getSessionFactory().getCurrentSession();
        sessionadd.beginTransaction();
        Sprzedawca sp = new Sprzedawca(nazwa, miejscowosc, kod, adres, nip, bank, numerKonta);
        sessionadd.save(sp);
        sessionadd.getTransaction().commit();
    }

    public static Sprzedawca update(int id, String nazwa, String miejscowosc, String kod, String adres, String nip, String bank, String numerKonta){
        try{
            get();
            Session session = HibernateUtil.getSessionFactory().getCurrentSession();
            session.beginTransaction();            
            Sprzedawca sp = new Sprzedawca(nazwa, miejscowosc, kod, adres, nip, bank, numerKonta);
            sp.setId(1);
            session.update(sp);
            session.getTransaction().commit();
            Out.println("Update successfully!");
            }catch(Exception e){
                if(e.getClass() == IndexOutOfBoundsException.class)
                add(nazwa, miejscowosc, kod, adres, nip, bank, numerKonta);
                else
                Error.println(e);
            }
        return get();
    }
}


