/*
 * DdFakturyAboutBox.java
 */

package ddfaktury.ui;

import com.sun.java.swing.plaf.nimbus.FileChooserPainter;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileView;
import javax.swing.plaf.FileChooserUI;
import javax.swing.plaf.basic.BasicFileChooserUI;
import org.jdesktop.application.Action;

public class ustawienia extends javax.swing.JDialog {
    String program;

    //Create a file chooser
    final JFileChooser fc = new JFileChooser();

    //In response to a button click:
    int returnVal;

    public ustawienia(java.awt.Frame parent, String aktualnyProgram) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        program = aktualnyProgram;
        jTextField1.setText(program);
    }

    @Action public void anuluj() {
        wyczysc();
        dispose();
    }

    @Action public void zapisz() {
        program = jTextField1.getText();
        File konfiguracja = new File("ddFaktury.conf");
          if(konfiguracja.exists()){
              try {
                    System.out.println("Konfiguracja istnieje");
                    konfiguracja.createNewFile();
                    PrintWriter wypelnij = new PrintWriter(konfiguracja);
                        wypelnij.println(program);
                    wypelnij.close();
                  } catch (IOException ex) {
                        System.err.println(DdFakturyApp.class.getName()+ex.toString());
                    }
            System.out.println("Plik z konfiguracją został zmodyfikowany.");
          }else{
              try {
                    konfiguracja.createNewFile();
                    PrintWriter wypelnij = new PrintWriter(konfiguracja);
                        wypelnij.println(program);
                    wypelnij.close();
                  } catch (IOException ex) {
                        System.err.println(DdFakturyApp.class.getName()+ex.toString());
                    }
              System.out.println("Plik z konfiguracją został stworzony.");
              System.out.println("Plik z konfiguracją został wypełniony odpowiednimi danymi.");
          }
        wyczysc();
        dispose();
    }

    @Action 
    public void test(){
        try {
                Runtime.getRuntime().exec(jTextField1.getText());
                jLabel3.setForeground(Color.green);
                jLabel3.setText("OK");
            } catch (IOException ex) {
               System.err.println(DdFakturyApp.class.getName()+ex.toString());
               jLabel3.setForeground(Color.red);
               jLabel3.setText("Błąd");
            }
        }

    private void wyczysc(){
            org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ddfaktury.ui.DdFakturyApp.class).getContext().getResourceMap(ustawienia.class);

            jLabel3.setForeground(Color.black);
            jLabel3.setText(resourceMap.getString("jLabel3.text"));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        closeButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        closeButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jFileChooser1.setName("jFileChooser1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ddfaktury.ui.DdFakturyApp.class).getContext().getResourceMap(ustawienia.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ddfaktury.ui.DdFakturyApp.class).getContext().getActionMap(ustawienia.class, this);
        closeButton.setAction(actionMap.get("anuluj")); // NOI18N
        closeButton.setIcon(resourceMap.getIcon("closeButton.icon")); // NOI18N
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        closeButton1.setAction(actionMap.get("zapisz")); // NOI18N
        closeButton1.setIcon(resourceMap.getIcon("closeButton1.icon")); // NOI18N
        closeButton1.setText(resourceMap.getString("closeButton1.text")); // NOI18N
        closeButton1.setName("closeButton1"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wybierz swój program...", "Przeglądarka dokumentów Evince", "Adobe Acrobat Reader 7.0", "Adobe Acrobat Reader 8.0", "Adobe Acrobat Reader 9.0", "Adobe Acrobat Reader 10.0", "Foxit Reader", "Inny" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        closeButton2.setAction(actionMap.get("test")); // NOI18N
        closeButton2.setIcon(resourceMap.getIcon("closeButton2.icon")); // NOI18N
        closeButton2.setText(resourceMap.getString("closeButton2.text")); // NOI18N
        closeButton2.setName("closeButton2"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                        .addComponent(closeButton2)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton1)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(closeButton1)
                    .addComponent(closeButton2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        switch (jComboBox1.getSelectedIndex()){
            case 1: jTextField1.setText("evince "); ; break;
            case 2: jTextField1.setText("C:\\Program Files\\Adobe\\Reader 7.0\\Reader\\AcroRd32.exe "); break;
            case 3: jTextField1.setText("C:\\Program Files\\Adobe\\Reader 8.0\\Reader\\AcroRd32.exe "); break;
            case 4: jTextField1.setText("C:\\Program Files\\Adobe\\Reader 9.0\\Reader\\AcroRd32.exe "); break;
            case 5: jTextField1.setText("C:\\Program Files\\Adobe\\Reader 10.0\\Reader\\AcroRd32.exe "); break;
            case 6: jTextField1.setText("C:\\Program Files\\Foxit Software\\Foxit Reader\\Foxit Reader.exe "); break;
            case 7: jTextField1.setText("other.exe "); ; break;
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            program = file.getPath();file.getName();
            System.out.println("Opening: " + file.getName() + ".");
        } else {
            System.out.println("Open command cancelled by user.");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jTextField1.setText(program);
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_formWindowActivated
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton closeButton1;
    private javax.swing.JButton closeButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
